-- AlterTable
ALTER TABLE `Order` MODIFY `KundRef2` VARCHAR(191) NULL,
    MODIFY `OrdLevAdr1` VARCHAR(191) NULL,
    MODIFY `OrdLevAdr3` VARCHAR(191) NULL,
    MODIFY `OrdLevAdr4` VARCHAR(191) NULL,
    MODIFY `Saljare` VARCHAR(191) NULL;
